### ISSUE TITLE
.env

### ISSUE THREAD

**Issue by Eyaaaaaa** [fireinsect/nonebot-plugin-ocgbot-v2#1]

**Comment by Eyaaaaaa** [comment]
另外 ，插件引入成功了，也在自动加载了默认的文件夹到了lib 插件的文件夹中了。但是 输入指令例如 查饼图 等等。没有一个是有响应的。这种问题一般出在哪儿了呢

**Comment by fireinsect** [comment]
nonebot默认在指令前需要添加/，取消需要在env内修改

**Comment by Eyaaaaaa** [comment]
; 游戏王的路径path
STATIC_PATH="D:\MyCardLibrary\ygopro"

输入 查饼图等，后台并没有响应
![OB4UP_%`GN75624` VH `H7](https://github.com/fireinsect/nonebot-plugin-ocgbot-v2/assets/50950152/0306ddf1-9e66-40ce-81c2-3ad2d33cb205)
后台也没有回应，明明监听到了指令
![image](https://github.com/fireinsect/nonebot-plugin-ocgbot-v2/assets/50950152/64f66e7d-f9aa-4284-89e1-cfff35775a34)

**Comment by Eyaaaaaa** [comment]
![image](https://github.com/fireinsect/nonebot-plugin-ocgbot-v2/assets/50950152/b0b1103e-5c96-4a96-bb8b-c0d3f47c3890)
![image](https://github.com/fireinsect/nonebot-plugin-ocgbot-v2/assets/50950152/494ee71a-2271-4fa2-b8fe-eb6cd53a776b)
作者你好。我按照要求加了/ 也是没有回应 这个一般问题可能出在哪儿了呢

**Comment by fireinsect** [comment]
（狗头）昨天测试完上传忘记导包了，把包根目录下的文件都import到__init__里就行了
![image](https://github.com/fireinsect/nonebot-plugin-ocgbot-v2/assets/76525116/96f475ee-f593-4f52-9fd3-a836aab3ebf1)

**Comment by Eyaaaaaa** [comment]
好的，感谢。这边已经可用了，查卡功能好了
另外无伤大雅的一个小问题就是更新禁卡表的功能好像不能用，我看了编辑器那个import data update 应该是没生效。我手动拖拽ygo的禁卡表就行了。不用这个功能没事。就是和作者说一声。感谢修复

**Comment by fireinsect** [comment]
禁卡表有权限限制，请在env内写入SUPERUSERS条目

**Comment by Eyaaaaaa** [comment]
超管和path其实我都设置了。但是那个STATIC_PATH="D:\MyCardLibrary\ygopro"  不知道为什么没生效。后来就用lib的也无所谓。至于超管这个我应该设置了。我是看编辑器 那个禁卡表哪行代码出现了没有生效的提示，也的确测试没有生效。
这个无所谓。。。。因为。。。机器人挂了、、、、
![image](https://github.com/fireinsect/nonebot-plugin-ocgbot-v2/assets/50950152/c59475d8-47a7-4c7e-8b6c-16a7d0e96d6c)
【可以不用再战斗了.jpg】
