### ISSUE TITLE
Pic第一次似乎是下载失败，然后就不会自动下载了

### ISSUE THREAD

**Issue by ElainaFanBoy** [fireinsect/nonebot-plugin-ocgbot-v2#2]
```
猜一张卡
没找到对应图片~
咿呀？启动失败了呢
```

我这边`__init__.py`里的`deck_url = "https://gitee.com/fireinsect/image-save/raw/master/decks/"`手动打开为纯白网页，不过我手动进入`https://gitee.com/fireinsect/image-save/tree/master/decks/`倒是可以进入仓库

**Comment by fireinsect** [comment]
猜卡卡图同卡查卡图

**Comment by ElainaFanBoy** [comment]
> 猜卡卡图同卡查卡图

我这边随机一卡、查卡、猜一张卡都没有图片资源

**Comment by ElainaFanBoy** [comment]
> 猜卡卡图同卡查卡图

我是需要手动下载`https://gitee.com/fireinsect/image-save/tree/master/decks/`仓库里的内容放入指定的文件夹里吗

**Comment by fireinsect** [comment]
自动下载只会下载卡运使用的卡图，具体使用卡图请查看`配置`方法

**Comment by ElainaFanBoy** [comment]
> 自动下载只会下载卡运使用的卡图，具体使用卡图请查看`配置`方法

懂了，/cdb和/pics需要自己下载放进入是不

**Comment by fireinsect** [comment]
cdb存在默认数据（不保证更新），pics需要手动导入，或者在env中写入文件夹绝对地址
