### ISSUE TITLE
连接至gocq成功但是无法响应指令

### ISSUE THREAD

**Issue by HuanKongzzz** [fireinsect/nonebot-plugin-ocgbot-v2#4]
以及没有找到.env文件（

**Comment by fireinsect** [comment]
抱歉！最近忙于学业没有关注github消息！
介于您的情况可以查看是否正确使用nonebot创建机器人，nonebot在init的同时会自动创建env环境文件。
其次指令无反应第一先去考虑是否正确连接qq登录方案（如cqhttp），如果连接成功，可能是nonebot自带的指令前缀的问题，可以查看buildGuide的Q3问题

**Comment by 512434** [comment]
没有卡图该如何解决，静态路径已添加

**Comment by fireinsect** [comment]
ygopro目录下的pics文件夹直接拖到静态路径目录下即可

**Comment by 512434** [comment]
请问如何导入先行卡，有下载地址吗？

**Comment by fireinsect** [comment]
先行卡数据需要自己找，以压缩文件方式打开先行卡的ypk文件，导出pics文件夹(卡图)以及叫做release的cdb文件，将cdb文件改名为pre-release.cdb，覆盖项目原文件（或者自己指定目录，防止在 `目录/cdb` 下）

**Comment by 512434** [comment]
> 先行卡数据需要自己找，以压缩文件方式打开先行卡的ypk文件，导出pics文件夹(卡图)以及叫做release的cdb文件，将cdb文件改名为pre-release.cdb，覆盖项目原文件（或者自己指定目录，放置在 `目录/cdb` 下）
谢谢大佬有空回我，我试试

**Comment by 512434** [comment]
试了下，还是不行，查询不到数据
https://mycard.moe/ygopro/arena/#/superpre下载超先行补丁，解压
把里面的test-release.cdb改名为pre-release.cdb;
最后pics文件夹和pre-release.cdb分别上传到指定目录下;
重新加载机器人，查卡恶魔光来
回复查询失败；
大佬，知道问题出在哪里吗？

**Comment by fireinsect** [comment]
有截图嘛

**Comment by 512434** [comment]
大佬有Q群吗？我加下，教教我

**Comment by fireinsect** [comment]
项目主页有

**Comment by 512434** [comment]
Q群没找到，倒是看到了大佬的博客

**Comment by fireinsect** [comment]
`这个`项目主页有

**Comment by fireinsect** [comment]
根据你的描述，这里推测可能出现的问题为图片索引出现问题，可能原因是图片存放位置错误，在项目目录（或自己制定目录下）应存在 `目录/pics`文件夹，文件夹内存放图片文件

**Comment by fireinsect** [comment]
根据你的描述，这里推测可能出现的问题为图片索引出现问题，可能原因是图片存放位置错误，在项目目录（或自己制定目录下）应存在 `目录/pics`文件夹，文件夹内存放图片文件
