### ISSUE TITLE
 Failed to import "nonebot_plugin_ocgbot_v2"

### ISSUE THREAD

**Issue by liangshppo** [fireinsect/nonebot-plugin-ocgbot-v2#5]
使用完nb plugin install nonebot-plugin-ocgbot-v2指令后用nb run运行会提示没导入nonebot_plugin_ocgbot_v2

**Comment by Sunhomen** [comment]
+1，请问有解决掉吗

**Comment by fireinsect** [comment]
有截图嘛

**Comment by Sunhomen** [comment]
> 有截图嘛

![Uploading 1714129199031.png…]()

**Comment by Sunhomen** [comment]
> 有截图嘛

提示的是这个

**Comment by fireinsect** [comment]
我测试了一下，原因是lxml最近把lxml-html-clean分支了出去
请使用 pip install lxml[html_clean] 来解决

**Comment by Sunhomen** [comment]
> 我测试了一下，原因是lxml最近把lxml-html-clean分支了出去 请使用 pip install lxml[html_clean] 来解决

![1714131257130](https://github.com/fireinsect/nonebot-plugin-ocgbot-v2/assets/109470730/c83a94fb-cfd4-4b50-8208-7f79a3fe242d)
安装后还是不行

**Comment by fireinsect** [comment]
依次输入
 pip install lxml
pip install lxml_html_clean
试试

**Comment by liangshppo** [comment]
依次输入
pip install lxml
pip install lxml_html_clean
后解决问题运行起来了，谢谢解答

**Comment by Sunhomen** [comment]
> 依次输入 pip install lxml pip install lxml_html_clean 试试

![1714133511303](https://github.com/fireinsect/nonebot-plugin-ocgbot-v2/assets/109470730/e328248d-8b7b-4561-8a43-2283215a19ce)
安装后依然不行，难不成是我操作步骤有问题还是？

**Comment by fireinsect** [comment]
你这个情况应该是没有进环境，在nb run 同一窗口输入

**Comment by Sunhomen** [comment]
> 你这个情况应该是没有进环境，在nb run 同一窗口输入
![1714189164199](https://github.com/fireinsect/nonebot-plugin-ocgbot-v2/assets/109470730/2ee197de-fbca-4af0-9bf7-ca772320c723)
同样的错误，我python是3.9和这个有关系吗

**Comment by Sunhomen** [comment]
![1714189660707](https://github.com/fireinsect/nonebot-plugin-ocgbot-v2/assets/109470730/1ed96c5c-0464-4930-8dca-0685ce146534)

**Comment by fireinsect** [comment]
![Screenshot_20240427_120025](https://github.com/fireinsect/nonebot-plugin-ocgbot-v2/assets/76525116/22249ca2-11c9-4796-9a0f-520653bf0287)
使用你绿色字体目录下的pip 代替指令中的pip
如  C:/xxxx/xxx/pip install

**Comment by Sunhomen** [comment]
> 我解决了lxml的问题后又出现了requests_html的问题 ![image](https://private-user-images.githubusercontent.com/117303687/326373841-d5aabe31-1a6d-432b-aae4-2ebedb5ee81e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzODE0NTYsIm5iZiI6MTcxNDM4MTE1NiwicGF0aCI6Ii8xMTczMDM2ODcvMzI2MzczODQxLWQ1YWFiZTMxLTFhNmQtNDMyYi1hYWU0LTJlYmVkYjVlZTgxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQwODU5MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZDMxYTMwMTRkNGZkZTdiMzdiMmRhMWJkNTM5NDgxNjQzYzQ1Y2VhNGFlYTk2OWViZjllYzJlM2FlNDQxZTZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.US5MjFVjNY1Ki2wyR8jLZetI-jcaRP_FYH

> ![Screenshot_20240427_120025](https://private-user-images.githubusercontent.com/76525116/326152007-22249ca2-11c9-4796-9a0f-520653bf0287.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzODE1MDQsIm5iZiI6MTcxNDM4MTIwNCwicGF0aCI6Ii83NjUyNTExNi8zMjYxNTIwMDctMjIyNDljYTItMTFjOS00Nzk2LTlhMGYtNTIwNjUzYmYwMjg3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA5MDAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmODAwODE5MGJkZGVmMDNiMTM0MWI3Mzc0OGRmNDJlYzY1ZDYwYTBmMWViYWIyZjNkZDAzODVlNzg3MzM0ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7yDmd5PBCn7mLLgICmSZ589uM0Y_W3clo1KYHlpM-Cc) 使用你绿色字体目录下的pip 代替指令中的pip 如 C:/xxxx/xxx/pip install

**感谢已解决，就是一直账号被风控******

**Comment by fireinsect** [comment]
> 我解决了lxml的问题后又出现了requests_html的问题 ![image](https://private-user-images.githubusercontent.com/117303687/326373841-d5aabe31-1a6d-432b-aae4-2ebedb5ee81e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzODM0NzksIm5iZiI6MTcxNDM4MzE3OSwicGF0aCI6Ii8xMTczMDM2ODcvMzI2MzczODQxLWQ1YWFiZTMxLTFhNmQtNDMyYi1hYWU0LTJlYmVkYjVlZTgxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQwOTMyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjMyNjBkNzg2Y2ZjNDMyNDczYWZkZWY5OTY3MTJmYWM5ZGVkNzNjZDYxZjgxODllNDI0OTA0NTQ4YzU3ZTE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uVys0KbjqWiCtY1a7rHBxad8o7BrfQTNu4NBn60PKsA)

  出现lxml问题的原因就是request_html以来的问题，你这里是直接缺少了request_html
