### ISSUE TITLE
猜一张卡 会报错

### ISSUE THREAD

**Issue by Sunhomen** [fireinsect/nonebot-plugin-ocgbot-v2#6]
/猜一张卡
![e24f21966c2db13606be81042e0ff0b](https://github.com/fireinsect/nonebot-plugin-ocgbot-v2/assets/109470730/3d5eabc4-46cd-4b93-b639-9310ee78ac31)

**Comment by fireinsect** [comment]
[Q1：机器人搭建完后没有卡图怎么办？](https://github.com/fireinsect/doc_save/blob/master/ocg-bot-v2-BuildGuide.md#q1%E6%9C%BA%E5%99%A8%E4%BA%BA%E6%90%AD%E5%BB%BA%E5%AE%8C%E5%90%8E%E6%B2%A1%E6%9C%89%E5%8D%A1%E5%9B%BE%E6%80%8E%E4%B9%88%E5%8A%9E) 同理，出现该问题的原因是你本地没有对应的卡图（猜卡自然需要卡图），请自行导入，这里难以提供稳定的卡图来源。
下个版本可能尝试去主动获取卡图
